-- Create roles
CREATE ROLE DATA_ENGINEER;
CREATE ROLE DATA_SCIENTIST;
CREATE ROLE DATA_ANALYST;

-- Create user
CREATE USER Rayyan
  PASSWORD = 'StrongPassword123!'  -- replace with secure password
  LOGIN_NAME = 'user_email'
  DEFAULT_ROLE = DATA_ANALYST
  DEFAULT_WAREHOUSE = ECOMMERCE
  MUST_CHANGE_PASSWORD = TRUE;


-- Grant roles to Rayyan
GRANT ROLE DATA_ANALYST TO USER Rayyan;
-- You can grant multiple roles if needed
-- GRANT ROLE DATA_SCIENTIST TO USER Rayyan;

GRANT USAGE ON DATABASE ECOMMERCE_DW TO ROLE DATA_ANALYST;
GRANT USAGE ON SCHEMA ECOMMERCE_DW.analytics TO ROLE DATA_ANALYST;
-- Grant read-only access on a single table
GRANT SELECT ON TABLE ecommerce_dw.analytics.mart_sales_overview TO ROLE DATA_ANALYST;


ALTER USER Rayyan SET DEFAULT_WAREHOUSE = ECOMMERCE;

GRANT USAGE ON WAREHOUSE ECOMMERCE TO ROLE DATA_ANALYST;

